# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: ghcr.io/hassio-addons/base:18.1.4
  amd64: ghcr.io/hassio-addons/base:18.1.4

labels:
  org.opencontainers.image.title: "Home Assistant Add-on: CarConnectivity"
  org.opencontainers.image.description: "Addon version of Carconnectivity made by Till (see https://github.com/jlachance/CarConnectivity) throught MQTT"
  org.opencontainers.image.source: "https://github.com/jlachance/carconnectivity-addon"
  org.opencontainers.image.licenses: "Apache License 2.0"

args:
  NGINX_VERSION: "1.26.3"
  AUDI_VERSION: "v0.2.0"
  SEAT_VERSION: "v0.4.8"
  SKODA_VERSION: "v0.9"
  VW_VERSION: "v0.9.3"
  VWNA_VERSION: ""
  TRONITY_VERSION: "v0.6.4"
  VOLVO_VERSION: "v0.1a1"
  ABRP_VERSION: "v0.6"
  MQTT_VERSION: "v0.8.1"
  MQTTHA_VERSION: "v0.4.1"
  WEBUI_VERSION: "v0.5.3"
  CC_VERSION: "v0.9.2"